### ISSUE TITLE
EditorConfigを付与した方がいい

### ISSUE THREAD

**Issue by g00cey** [kotarou1192/Co-review#30]
レビュー時に最終行は空行があった方がいいなどの指摘があったので、EditorConfigの導入するのはいかがでしょうか。

**Comment by ikngtty** [comment]
Rubocop ってそこまでは見てくれないのかな。今は Rubocop 導入されてるので、そこで吸収できたらしちゃいたいけど。
あと、EditorConfig とは別に VSCode の設定は最終行改行にしておいてほしい。てかデフォルトはそうだった気がするので、どういうプロセスで最終行無改行が生まれてしまったのか気になる。

**Comment by g00cey** [comment]
rubocopで吸収する予定理解しました。

私のVSCodeでも最終行が空行にならないようになっていました。
この辺環境違いで出てきてしまうので、

- .vscode(Co-review配下)で統一したいものをソースコード管理と同様に行う
- エディタで異なっちゃうとあれなので、editorconfig入れる
- rubocopに設定を追加して、それ見てね。

全部取り入れるかはまた鯖で相談ということでissueクローズ致します。

**Comment by ikngtty** [comment]
@t1una 

> 私のVSCodeでも最終行が空行にならないようになっていました。

あれ、どっち？自分の環境はデフォルトで最後に改行入る設定なんだけども多分。
（俺の１個前の発言、一回逆に書いちゃって後から編集したから、それで行き違い生じてるかも。）
