### ISSUE TITLE
ユーザーページのアクションを洗い出す

### ISSUE THREAD

**Issue by g00cey** [kotarou1192/Co-review#42]

**Comment by kotarou1192** [comment]
[header](https://github.com/kotarou1192/Co-review/wiki/page-layouts#header)
[user_page](https://github.com/kotarou1192/Co-review/wiki/page-layouts#user_page)
↑でアクションの洗い出しを行ってます。
不足分はありますでしょうか？
@radix-soup

**Comment by ghost** [comment]
https://github.com/kotarou1192/Co-review/issues/43#issuecomment-638238967
上記リンクでの説明と同様の理由でこちらもクローズします．
