### ISSUE TITLE
トップページのアクションを洗い出す

### ISSUE THREAD

**Issue by g00cey** [kotarou1192/Co-review#43]

**Comment by kotarou1192** [comment]
[top_page](https://github.com/kotarou1192/Co-review/wiki/page-layouts#%E7%94%BB%E9%9D%A2%E8%A8%AD%E8%A8%88)
[header](https://github.com/kotarou1192/Co-review/wiki/page-layouts#header)
↑でアクションの洗い出しを行ってます。
不足分はありますでしょうか？
@radix-soup

**Comment by ghost** [comment]
現状は設計段階なので，そこまで"仕様"に拘らなくていいと思うよ．
仕様を固めた結果，柔軟性のない設計になってしまっては元も子もないし，何より実際に手を動かすまでにかかる時間が間延びして退屈でしょう．
上に載せてもらったドキュメントで十分な完成度だと思うので，一旦先のドキュメントに記載されてる通りに作って，動かすところまで持っていきましょう．
