### ISSUE TITLE
ユーザーストーリーマップ作製

### ISSUE THREAD

**Issue by g00cey** [kotarou1192/Co-review#44]

**Comment by kotarou1192** [comment]
タスクを減らし、やることを明確にしていきたいため、イシューの整理中です。
それに伴いこのイシューにコメントを投稿します。

今までの打ち合わせでCoreviewで実現する機能は決まっていると思います。
それをもとに画面設計やDB設計などをはじめているため、初回リリース時のユーザーストーリーマップは決まっているという認識でいました。
そのため、いったんクローズしてもよいでしょうか？
（機能追加等でリオープンになることも想定しています、リオープンするかどうかは運用フロー次第）

**Comment by ghost** [comment]
> 画面設計やDB設計などをはじめているため、初回リリース時のユーザーストーリーマップは決まっているという認識

細かい仕様を起こしてあるので，それを有効に活用すれば十分な精度のユーザーストーリーマップができる，という意見であれば同意です．

クローズしていいですよ．というか僕が閉じちゃうね．
