### ISSUE TITLE
Discord 上の GitHub 通知はチャンネル分けた方がいいか

### ISSUE THREAD

**Issue by g00cey** [kotarou1192/Co-review#52]
個人的には、今のままでも問題感じないですが、他のプロジェクトでも使用するならば検討したい。

**Comment by ghost** [comment]
結論：チャンネルは分けない(現行のまま)
理由：
- 通知内容がTLとなって議論に文脈がつく
- 通知内容のメッセージリンクをコピーすることで議論が明晰かつ self-contained になる
- 現状，co-review 以外の対象プロダクトが存在せず，話題が発散する可能性が低い
