### ISSUE TITLE
画面設計書をWikiに記載する

### ISSUE THREAD

**Issue by g00cey** [kotarou1192/Co-review#66]
# 概要

MTGで決定した画面をベースに画面設計書をWikiに記載してください。
なお、一度以前のMTGで発表のあった画面設計書を本issueに添付願います。

**Comment by kotarou1192** [comment]
![mindmap](https://user-images.githubusercontent.com/51397938/81480101-6a887700-9262-11ea-81f8-842ff7f8bcf9.png)
![post_request](https://user-images.githubusercontent.com/51397938/81480102-6c523a80-9262-11ea-862f-fcc92c523d99.png)
![request](https://user-images.githubusercontent.com/51397938/81480104-6eb49480-9262-11ea-9941-ee217827631d.png)
![search_result](https://user-images.githubusercontent.com/51397938/81480105-6fe5c180-9262-11ea-9978-057a921b173a.png)
![top](https://user-images.githubusercontent.com/51397938/81480111-75430c00-9262-11ea-9594-269591bfb383.png)
![user_page](https://user-images.githubusercontent.com/51397938/81480117-78d69300-9262-11ea-9656-c02c7c04c70a.png)

**Comment by g00cey** [comment]
https://github.com/kotarou1192/Co-review/wiki/page-layouts

画面設計書・遷移図が上がったので完了

**Comment by ikngtty** [comment]
画面遷移図が混線しててクソ分かりづらいように見える
